<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'TpMinify\Module'                 => __DIR__ . '/Module.php',
  'TpMinify\Controller\Index'       => __DIR__ . '/src/TpMinify/Controller/Index.php',
  'TpMinify\View\Helper\HeadScript' => __DIR__ . '/src/TpMinify/View/Helper/HeadScript.php',
);
